namespace Ava.Shared.Models.Kernel.SysVar;

public class InternalSupportTicket
{
    // autogenerated on page load
    public string IssueId { get; set; } = string.Empty;
    public string Subject { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string UserId { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
}