namespace Ava.Shared.Models.Static;

public static class AustralianCities
{
    public static Dictionary<string, string> AusCities { get; set; } = new()
    {
        { "Adelaide, Australia", "ADL" },
        { "Albury, Australia", "ABX" },
        { "Alice Springs, Australia", "ASP" },
        { "Armidale, Australia", "ARM" },
        { "Ayers Rock (Uluru), Australia", "AYQ" },
        { "Ballina (Byron), Australia", "BNK" },
        { "Barcaldine, Australia", "BCI" },
        { "Bendigo, Australia", "BXG" },
        { "Blackall, Australia", "BKQ" },
        { "Brisbane, Australia", "BNE" },
        { "Broken Hill, Australia", "BHQ" },
        { "Broome, Australia", "BME" },
        { "Bundaberg, Australia", "BDB" },
        { "Burnie, Australia", "BWT" },
        { "Busselton, Australia", "BQB" },
        { "Cairns, Australia", "CNS" },
        { "Canberra, Australia", "CBR" },
        { "Cloncurry, Australia", "CNJ" },
        { "Coffs Harbour, Australia", "CFS" },
        { "Darwin, Australia", "DRW" },
        { "Devonport, Australia", "DPO" },
        { "Dubbo, Australia", "DBO" },
        { "Emerald, Australia", "EMD" },
        { "Exmouth (Learmonth), Australia", "LEA" },
        { "Fraser Coast (Hervey Bay), Australia", "HVB" },
        { "Geraldton, Australia", "GET" },
        { "Gladstone, Australia", "GLT" },
        { "Gold Coast (Coolangatta), Australia", "GLT" },
        { "Gove (Nhulunbuy), Australia", "GOV" },
        { "Griffith, Australia", "GFF" },
        { "Hamilton Island, Australia", "HTI" },
        { "Hobart, Australia", "HBA" },
        { "Horn Island, Australia", "HID" },
        { "Kalgoorlie, Australia", "KGI" },
        { "Kangaroo Island (Kingscote), Australia", "KGC" },
        { "Karratha, Australia", "KTA" },
        { "Kununurra, Australia", "KNX" },
        { "Launceston, Australia", "LST" },
        { "Longreach, Australia", "LRE" },
        { "Lord Howe Island, Australia", "LDH" },
        { "Mackay, Australia", "MKK" },
        { "Melbourne (Avalon), Australia", "AVV" },
        { "Melbourne (Tullamarine), Australia", "MEL" },
        { "Merimbula, Australia", "MIM" },
        { "Mildura, Australia", "MQL" },
        { "Miles, Australia", "WLE" },
        { "Moranbah, Australia", "MOV" },
        { "Moree, Australia", "MRZ" },
        { "Mount Gambier, Australia", "MGB" },
        { "Mount Isa, Australia", "ISA" },
        { "Newcastle (Williamtown), Australia", "NTL" },
        { "Newman, Australia", "ZNE" },
        { "Onslow, Australia", "ONS" },
        { "Orange, Australia", "OAG" },
        { "Paraburdoo, Australia", "PBO" },
        { "Perth, Australia", "PER" },
        { "Port Hedland, Australia", "PHE" },
        { "Port Lincoln, Australia", "PLO" },
        { "Port Macquarie, Australia", "PQQ" },
        { "Rockhampton, Australia", "ROK" },
        { "Sunshine Coast (Masroochydore), Australia", "MCY" },
        { "Sydney, Australia", "SYD" },
        { "Tamworth, Australia", "TMW" },
        { "Toowoomba (Brisbane West Wellcamp), Australia", "WTB" },
        { "Townsville, Australia", "TSV" },
        { "Wagga Wagga, Australia", "WGA" },
        { "Weipa, Australia", "WEI" },
        { "Whistunday Coast (Prosperine), Australia", "PPP" },
        { "Whyalla, Australia", "WYA" },
    };
}
